// Package websocket_api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package websocket_api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	. "github.com/kurtosis-tech/kurtosis/api/golang/http_rest/api_types"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get enclave's services logs
	// (GET /enclaves/{enclave_identifier}/logs)
	GetEnclavesEnclaveIdentifierLogs(ctx echo.Context, enclaveIdentifier EnclaveIdentifier, params GetEnclavesEnclaveIdentifierLogsParams) error
	// Get service logs
	// (GET /enclaves/{enclave_identifier}/services/{service_identifier}/logs)
	GetEnclavesEnclaveIdentifierServicesServiceIdentifierLogs(ctx echo.Context, enclaveIdentifier EnclaveIdentifier, serviceIdentifier ServiceIdentifier, params GetEnclavesEnclaveIdentifierServicesServiceIdentifierLogsParams) error
	// Get Starlark execution logs
	// (GET /starlark/executions/{starlark_execution_uuid}/logs)
	GetStarlarkExecutionsStarlarkExecutionUuidLogs(ctx echo.Context, starlarkExecutionUuid StarlarkExecutionUuid) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetEnclavesEnclaveIdentifierLogs converts echo context to params.
func (w *ServerInterfaceWrapper) GetEnclavesEnclaveIdentifierLogs(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "enclave_identifier" -------------
	var enclaveIdentifier EnclaveIdentifier

	err = runtime.BindStyledParameterWithLocation("simple", false, "enclave_identifier", runtime.ParamLocationPath, ctx.Param("enclave_identifier"), &enclaveIdentifier)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter enclave_identifier: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEnclavesEnclaveIdentifierLogsParams
	// ------------- Required query parameter "service_uuid_set" -------------

	err = runtime.BindQueryParameter("form", true, true, "service_uuid_set", ctx.QueryParams(), &params.ServiceUuidSet)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter service_uuid_set: %s", err))
	}

	// ------------- Optional query parameter "follow_logs" -------------

	err = runtime.BindQueryParameter("form", true, false, "follow_logs", ctx.QueryParams(), &params.FollowLogs)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter follow_logs: %s", err))
	}

	// ------------- Optional query parameter "conjunctive_filters" -------------

	err = runtime.BindQueryParameter("form", true, false, "conjunctive_filters", ctx.QueryParams(), &params.ConjunctiveFilters)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter conjunctive_filters: %s", err))
	}

	// ------------- Optional query parameter "return_all_logs" -------------

	err = runtime.BindQueryParameter("form", true, false, "return_all_logs", ctx.QueryParams(), &params.ReturnAllLogs)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter return_all_logs: %s", err))
	}

	// ------------- Optional query parameter "num_log_lines" -------------

	err = runtime.BindQueryParameter("form", true, false, "num_log_lines", ctx.QueryParams(), &params.NumLogLines)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter num_log_lines: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetEnclavesEnclaveIdentifierLogs(ctx, enclaveIdentifier, params)
	return err
}

// GetEnclavesEnclaveIdentifierServicesServiceIdentifierLogs converts echo context to params.
func (w *ServerInterfaceWrapper) GetEnclavesEnclaveIdentifierServicesServiceIdentifierLogs(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "enclave_identifier" -------------
	var enclaveIdentifier EnclaveIdentifier

	err = runtime.BindStyledParameterWithLocation("simple", false, "enclave_identifier", runtime.ParamLocationPath, ctx.Param("enclave_identifier"), &enclaveIdentifier)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter enclave_identifier: %s", err))
	}

	// ------------- Path parameter "service_identifier" -------------
	var serviceIdentifier ServiceIdentifier

	err = runtime.BindStyledParameterWithLocation("simple", false, "service_identifier", runtime.ParamLocationPath, ctx.Param("service_identifier"), &serviceIdentifier)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter service_identifier: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEnclavesEnclaveIdentifierServicesServiceIdentifierLogsParams
	// ------------- Optional query parameter "follow_logs" -------------

	err = runtime.BindQueryParameter("form", true, false, "follow_logs", ctx.QueryParams(), &params.FollowLogs)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter follow_logs: %s", err))
	}

	// ------------- Optional query parameter "conjunctive_filters" -------------

	err = runtime.BindQueryParameter("form", true, false, "conjunctive_filters", ctx.QueryParams(), &params.ConjunctiveFilters)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter conjunctive_filters: %s", err))
	}

	// ------------- Optional query parameter "return_all_logs" -------------

	err = runtime.BindQueryParameter("form", true, false, "return_all_logs", ctx.QueryParams(), &params.ReturnAllLogs)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter return_all_logs: %s", err))
	}

	// ------------- Optional query parameter "num_log_lines" -------------

	err = runtime.BindQueryParameter("form", true, false, "num_log_lines", ctx.QueryParams(), &params.NumLogLines)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter num_log_lines: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetEnclavesEnclaveIdentifierServicesServiceIdentifierLogs(ctx, enclaveIdentifier, serviceIdentifier, params)
	return err
}

// GetStarlarkExecutionsStarlarkExecutionUuidLogs converts echo context to params.
func (w *ServerInterfaceWrapper) GetStarlarkExecutionsStarlarkExecutionUuidLogs(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "starlark_execution_uuid" -------------
	var starlarkExecutionUuid StarlarkExecutionUuid

	err = runtime.BindStyledParameterWithLocation("simple", false, "starlark_execution_uuid", runtime.ParamLocationPath, ctx.Param("starlark_execution_uuid"), &starlarkExecutionUuid)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter starlark_execution_uuid: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetStarlarkExecutionsStarlarkExecutionUuidLogs(ctx, starlarkExecutionUuid)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/enclaves/:enclave_identifier/logs", wrapper.GetEnclavesEnclaveIdentifierLogs)
	router.GET(baseURL+"/enclaves/:enclave_identifier/services/:service_identifier/logs", wrapper.GetEnclavesEnclaveIdentifierServicesServiceIdentifierLogs)
	router.GET(baseURL+"/starlark/executions/:starlark_execution_uuid/logs", wrapper.GetStarlarkExecutionsStarlarkExecutionUuidLogs)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaX2/bOBL/KgTvgLsDVCvXfVis34Ku2w0ulwSJe12gDbS0NLLZUKTKP259hr/7gRQl",
	"SxYty2mA4oDNS2xq/pPz42jGW5yKohQcuFZ4usUlkaQADdJ9SwX/bHiq6RqSnLJ6mXI8xV8MyA2OMCcF",
	"4GmQNMIqXUFBHI+GwjH/VUKOp/gv8V5xXJGp+FosrymHt44f7yKsN6UVTqQkG7zbRRh4ysgaEpoB1zSn",
	"IK3MDFQqaampsJa9f3/1a4TUSkgNHDJUfRcSWVORyJFeAfKCcFR5UxK92jsT0BJhCV8MlZDhqZYG2r55",
	"K5WWlC+dmblgTHxNmFgeDVibJCBsIQQDwp00bgpLlzDK4ai8LlFAIuUaljasO+uLNpInhLFBGw/JTtip",
	"QK5pOrw58xUgT4f2dPWupIJrQjlIpFdE+6WiIDyz+2lYhhaA4BukRkOGKA9vX8CO87avFmAMzRIF+lh8",
	"enRDapoMONAXOOVKE8mIfEoqV6ngTkU4mobTL6YTTC2QliR9qg56LcLGmKAHLxpVYmxalCR9IssjqXDM",
	"lHMC6g6cKgVX1fG9Efr2yeOLBu7CS8qS0ZRYBfFnZZ3btiQOgca9F33Fc1EpO4ADDt9KSO2BASlFlQCe",
	"2cr2oOPQT4oSpKaVmcyvjt24CGtagNKkKE/ZPG8Iq+DUkfxYKW1LemzUiMVnSLXV08XJnuH2M9FCjoTb",
	"25rcegDfdFISrUHycG60jW0UHTAO2Hzbsg24KayYX29nD8mb25v55dVNMp/9PsdRtXZzOw+u12v/vpy/",
	"+S25n72b/R5iaT/em7Tfvs7J6UUxFZnb/lzIgmg8xYZy/dNrHPUANcIFKGVT6PghGXeG55b2MMpOwF5H",
	"VFkWinFHTCvAs/v723sc4aubt7c4wh8u72+ubt4FY/JQQdq1vxW6IeFCJ7kw3IJdACFH50nNbS+VZLHp",
	"SHNgkGXUZi9hdx39Iw5zS10dl10gUjUMzhwi9ByFellwuM3x9OOw7lraFdcgSwna4VglexeN4/0PYTR7",
	"Bt+sxmXP9nh4fCpfHoeC0BXRj0YD/TAQruR4EoQsasgfQxvWIT9QP+RKOJXpkVWlpUmrayLEMt6jDvVJ",
	"h9qKRxDn4oTLA24QuTRFXdyPqsEDYi+9kFAqV5tDFgySg3j2UKD1PKmqixCRStQTLUvIQkVmhEuhaK3h",
	"TDfuataB/agMi1pxO+pix9aRG9REMrRRg0GRUEpQwC20rCEcGwWSEkb/C1lixa0JMyPObpArpHOkj3et",
	"HTq8UZkpeOdOPX6l5pTB0YDUpdlJOQe+NkKjutDyNo307R6UYXoQShJ5hKYV5zD56G0KsJ+DOcd52j73",
	"b7KA122iH3M5BG0Y8uze8LeUU7WCbLYOpqI0PMk9SQJhGpsdhifKpCkolRt2MiOF0aUZsc99ySdjEDD4",
	"RATupFhKUIESr/RPkvCdmRopgetEaSgbkvGFX4edm2JRvb6MgAMtNGGOTz0n8ft2d0WGTTsZ+W60TgS9",
	"rs7rt83ua2rzYt5UY6hmwNHZdej+mhpdR55VdbbP0FiePo6eoa2bs2MZPxDJq6M41sRc2BJ6v2+HZXkv",
	"I9YNwY8BwJ7+oVNYx6Nn49cTD8abf8hw0oFadcjuebuh0uR8RjS80tRd44FeUw1Lmmpmn/3LSC0UVeh+",
	"9jDPDUOXd1c4wmuQqkq9i8k/JxdWnSiBk5LiKf5pcjG5wJFrhrk4xL4nbL/sov3XeEWVFnJzuLzt95B3",
	"Y2hiIjXNSarVedQxEylhr2yBcyajhEJoeA6nf21X8bbfcT3T2Xhbf3xpGXEmvnImSDZKWN0NX1YtjS5E",
	"vwONCsM0LVkzQKib2QpZVpQK7i8Stpmg+YoqBDwrBeUapYQjpSWQwjVmHf1ig4DqFUiktLWeLz9xgj7A",
	"Qon0CbSVx8FBJvq7hFQUBfAMsn8gIRGDJUk36Lf5/M7LpXw5wZFvy1HBr7LK6pn32f+/ahy+rrr67anP",
	"kStmTxIHpiPH8LXF1esYjeBpz0hGkIdmUCPYDqccI1i6w5bd40GD+/XFxYu1t9sNuUB3+6GpE1FtAnZE",
	"OfGvFSHhjbVx1Yt3LXFTFMQCmTvnfpP/proH3CIusSnyETdHDruW04nEqqWMysIGWPbH/zy+M0D5BVBs",
	"UELsB1gvIKlGEhVvSyG1r1J3MVkTysiCMqpfwOXTGFjP7yzh/wHI+QxS/v8PRb/zuP7Evx+Gf+0z/t2g",
	"F84zU9pCdlzC+vr9LOLYD3bV87jirf+U0Gx3nohqg0br1WZPuqQcYl/B25VGZjMFsNEMD6VPQNfDASyJ",
	"HBG+H4jvB+XutwdfQQKinGpKNGTIKMqX6A8JWlJY+9EVURue/jH5xOcrQO6LrwIJRwv3awZlCsiQ4GyD",
	"BE8BEZ4h+FZSCYjkGqSnKasBvUSv0UoYqeqHElzKOA3noywaCbKf+HiU7c2MVG/lvaHZs6D12G8Nvhtf",
	"zhp8HHZq+j/QGAahLwaUfhEMChzNITjyg9U62F0Tr+3rIQK+plJwN4KIsJEMT/FK63Ia+9SbuNfIlVB6",
	"6mqMXWzfhyO8JpKSBfM9QiF9enkH8S8///wLjpp5s/vqLDo0406KrGoBoTdMmOyoRaox6dW2+l+l+CS1",
	"bJMn/04/SUURMrHF0rX0ovVnt/Jx978AAAD//94gHF8DJwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
